version: '3.9'

services:

  db:
    image: postgres:15.2-alpine
    ports:
      - 5431:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fantasy_club
    volumes:
      - ./volumen/dbData:/var/lib/postgresql/data
volumes:
  dbData:
    driver: local